spring:
  application:
    name: shipment
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb # http://localhost:8090/h2-console
    generate-unique-name: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8090
